load: "STARTUP"
main: "com.github.theprogmatheus.craftlib.bukkit.Main"
name: "CraftLib"
description: "A lightweight runtime library loader."
version: ${version}
api-version: 1.8
author: "TheProgMatheus"
website: "https://github.com/theprogmatheus/craftlib"